In [1]:
%load_ext autoreload
# %autoreload 2

Failed to read module file 'C:\Users\Alejandro\AppData\Local\Programs\Python\Python314\Lib\re\_casefix.py' for module 're._casefix': UnicodeDecodeError
Traceback (most recent call last):
  File "c:\Users\Alejandro\Desktop\Examen_II\.venv\Lib\site-packages\IPython\core\extensions.py", line 62, in load_extension
    return self._load_extension(module_str)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "c:\Users\Alejandro\Desktop\Examen_II\.venv\Lib\site-packages\IPython\core\extensions.py", line 77, in _load_extension
    mod = import_module(module_str)
  File "C:\Users\Alejandro\AppData\Local\Programs\Python\Python314\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1335, in 

In [2]:
%autoreload 2
from src import matriz_aumentada, gauss_jordan

A = [
    [1, 2, 3, 4],
    [2, 5, 6, 7],
    [3, 6, 8, 9],
    [4, 7, 9, 10],
]
b = [1, -2, 3, 4]

Ab = matriz_aumentada(A, b) # type: ignore
gauss_jordan(Ab)

[02-02 13:07:56][INFO][Alejandro] 2026-02-02 13:07:56.944237
[02-02 13:07:57][INFO][Alejandro] 2026-02-02 13:07:57.002044
[02-02 13:07:57][INFO][Alejandro] 2026-02-02 13:07:57.003218
[02-02 13:07:57][INFO][Alejandro] 
[[ 1.  2.  3.  4.  1.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0. -1. -3. -6.  0.]]
[02-02 13:07:57][INFO][Alejandro] 
[[ 1.  0.  3.  6.  9.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0. -3. -7. -4.]]
[02-02 13:07:57][INFO][Alejandro] 
[[ 1.  0.  0. -3.  9.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0.  0.  2. -4.]]
[02-02 13:07:57][INFO][Alejandro] 
[[ 1.  0.  0.  0.  3.]
 [ 0.  1.  0.  0. -6.]
 [ 0.  0. -1.  0. -6.]
 [ 0.  0.  0.  2. -4.]]


array([ 3., -6.,  6., -2.])

Resolver

In [3]:
import logging
from sys import stdout
from datetime import datetime
import os

logging.basicConfig(
    level=logging.INFO,
    format=f"[%(asctime)s][%(levelname)s][{os.environ.get('USERNAME')}] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)
logging.info(datetime.now())

[02-02 13:07:58][INFO][Alejandro] 2026-02-02 13:07:58.805144


In [13]:
import numpy as np
def inv_matrix(A: np.ndarray) -> np.ndarray:
    """Inversión de una matriz cuadrada mediante Gauss-Jordan.

    Parameters
    ----------
    A : np.ndarray
        Matriz cuadrada n x n.

    Returns
    -------
    np.ndarray
        Matriz inversa de A.

    Raises
    ------
    ValueError
        Si la matriz no es cuadrada o no es invertible.
    """
    A = np.array(A, dtype=float)

    A = A.astype(float)  # evitar división entera

    n, m = A.shape
    if n != m:
        raise ValueError("La matriz debe ser cuadrada")

    # Matriz aumentada [A | I]
    I = np.eye(n)
    M = np.hstack((A, I))

    # Proceso Gauss-Jordan
    for i in range(n):

        # Buscar pivote
        if M[i, i] == 0:
            for p in range(i + 1, n):
                if M[p, i] != 0:
                    M[[i, p]] = M[[p, i]]  # intercambio filas
                    break
            else:
                raise ValueError("La matriz no es invertible")

        # Normalizar fila pivote
        pivot = M[i, i]
        M[i] = M[i] / pivot

        # Eliminar resto de la columna
        for j in range(n):
            if j != i:
                factor = M[j, i]
                M[j] = M[j] - factor * M[i]

    # Extraer parte derecha
    A_inv = M[:, n:]
    return A_inv


## Ejemplos
* Ejemplo 1

In [ ]:
A = np.array([
    [1, 2, 3, 4],
    [2, 5, 6, 7],
    [3, 6, 8, 9],
    [4, 7, 9, 10],
])

# tiene como inversa
# A_inv =[[ 0.5, -0.5, -1.5,  1.5],
#        [-0.5,  1.5, -1.5,  0.5],
#        [-1.5, -1.5,  3.5, -1.5],
#        [ 1.5,  0.5, -1.5,  0.5]]

A_inv = inv_matrix(A)
print(A_inv)


[[ 0.5 -0.5 -1.5  1.5]
 [-0.5  1.5 -1.5  0.5]
 [-1.5 -1.5  3.5 -1.5]
 [ 1.5  0.5 -1.5  0.5]]


* Ejemplo 2

In [15]:
# La matriz A =
A = np.array([
    [4, 4, 5, 1],
    [3, 4, 2, 2],
    [2, 1, 4, 1],
    [3, 2, 5, 4],
])
# tiene como inversa
# A_inv =[[-34.,  31.,  52., -20.],
#         [ 19., -17., -29.,  11.],
#         [ 12., -11., -18.,   7.],
#         [  1.,  -1.,  -2.,   1.]]
A_inv = inv_matrix(A)
print(A_inv)

[[-34.  31.  52. -20.]
 [ 19. -17. -29.  11.]
 [ 12. -11. -18.   7.]
 [  1.  -1.  -2.   1.]]


## Ejercicios
* Ejercicio 1

In [16]:
A = np.array([[2, -3], [-1, 1]])

A_inv = inv_matrix(A)
print(A_inv)

[[-1. -3.]
 [-1. -2.]]


* Ejercicio 2

In [17]:
A = np.array([
    [4, 0, 0, 5],
    [1, 0, 4, 0],
    [3, 4, 1, 3],
    [1, 3, 3, 0],
])
A_inv = inv_matrix(A)
print(A_inv)

[[-36.  45.  60. -80.]
 [  3.  -4.  -5.   7.]
 [  9. -11. -15.  20.]
 [ 29. -36. -48.  64.]]


* Ejercicio 3

In [18]:
A = [
    [0, 0, 0, 0, 0, 0, 1, -1],
    [0, 1, -1, 1, 0, -1, 0, 1],
    [-1, -1, 0, 0, 2, 1, 0, 0],
    [-1, -1, -1, 1, 2, 0, 0, 1],
    [-1, 1, 1, 0, -1, -1, 0, 2],
    [0, 1, 0, 0, -1, -1, 0, 0],
    [1, -1, -1, 1, 2, 1, 0, 2],
    [2, 0, 0, 0, 0, 1, 2, 0],
]
A_inv = inv_matrix(A)
print(A_inv)

[[ 2. -1.  0. -1.  0.  2.  2. -1.]
 [ 0.  1.  1. -1.  0.  0.  0.  0.]
 [ 6. -1.  0. -3.  1.  1.  4. -3.]
 [ 6.  1. -1. -3.  1. -3.  3. -3.]
 [ 2. -1.  1. -1.  0.  3.  2. -1.]
 [-2.  2.  0.  0.  0. -4. -2.  1.]
 [-1.  0.  0.  1.  0.  0. -1.  1.]
 [-2.  0.  0.  1.  0.  0. -1.  1.]]


* Ejercicio 4

In [19]:
A = [
    [1, 0, 0, 0, -1, 0, 0, -1, 1, -1],
    [1, 1, 0, -1, -1, 1, 0, 0, 1, -1],
    [-1, 0, -1, 0, 0, 0, -1, 1, 0, 0],
    [0, 0, -1, 0, -1, -1, 1, 0, 1, 0],
    [-1, 0, 0, -1, 1, 1, 1, 1, 0, -1],
    [1, 0, 0, 1, -1, -1, -1, 1, -1, 0],
    [1, 1, 1, 0, 1, 0, -1, -1, -1, 1],
    [1, 1, 1, 1, 0, 0, 1, 1, 0, 0],
    [1, 1, 1, 1, 1, 0, -1, -1, 0, 0],
    [0, 0, -1, -1, -1, 0, 1, 1, 1, -1],
]
A_inv = inv_matrix(A)
print(A_inv)

[[ 14.  -8.   9.  -4.   0.  -4.   9.   7.  -8.   3.]
 [ -2.   2.  -1.   2.   1.   1.  -1.  -1.   1.  -2.]
 [-27.  14. -18.   5.  -2.   7. -17. -13.  16.  -2.]
 [ 12.  -6.   8.  -2.   1.  -3.   7.   6.  -7.   0.]
 [  6.  -4.   4.  -2.   0.  -2.   4.   3.  -3.   2.]
 [ 18.  -9.  12.  -4.   1.  -5.  11.   9. -11.   1.]
 [  8.  -4.   5.  -1.   1.  -2.   5.   4.  -5.   0.]
 [ -5.   2.  -3.   0.  -1.   1.  -3.  -2.   3.   1.]
 [-11.   5.  -7.   1.  -2.   2.  -7.  -5.   7.   1.]
 [  1.  -1.   1.  -1.  -1.  -1.   1.   1.  -1.   1.]]
